//events.js

export default [
  // {
  //   title: 'Event Example Title',
  //   start: '2023-07-22T14:00:00',
  //   end: '2023-07-22T15:30:00',
  //   location: '代沢地区会館',
  //   googleMapsUrl: 'https://goo.gl/maps/6Vu8mX3HmBWbEU8n8',
  //   description: 'Example description',
  // },
  // {
  //   title: 'Instagram Live Example',
  //   start: '2023-08-19T18:00:00',
  //   end: '2023-08-19T20:30:00',
  //   stream: true,
  //   location: 'Instagram',
  //   googleMapsUrl: null,
  //   instagramUrl: 'https://www.instagram.com/culturalfusionhub/',
  //   description: 'This is an Instagram Live Stream.',
  // },
  {
    title: 'Cultural Fusion Hub Meet up!',
    start: '2023-07-15T09:00:00',
    end: '2023-07-15T12:00:00',
    location: '代沢地区会館',
    stream: false,
    googleMapsUrl: 'https://goo.gl/maps/6Vu8mX3HmBWbEU8n8',
    instagramUrl: null,
    description:
      'ミックスキッズとそのママさん、パパさんの交流会。英語の本の読み聞かせもあります！おもちゃもたくさん準備していますので、お子様を連れて、お気軽にお越しください。お時間のある方は、交流会の後にランチや近場の夏祭りに行きましょう！',
  },
  {
    title: 'Field Trip',
    start: '2023-08-06T10:00:00',
    end: '2023-08-06T12:00:00',
    location: '消防博物館',
    stream: false,
    googleMapsUrl: 'https://goo.gl/maps/f1qV9NSW5iTZgPuAA',
    instagramUrl: null,
    description: 'ミックスの子供たちとパパさん、ママさんのための交流フィールドトリップ開催。歴代の消防車を見たり、ヘリコプターに乗ったりして子供たちを交流させましょう。',
  },
  {
    title: 'Instagram Live',
    start: '2023-08-20T18:00:00',
    end: '2023-08-20T20:30:00',
    stream: true,
    location: 'Instagram',
    googleMapsUrl: null,
    instagramUrl: 'https://www.instagram.com/culturalfusionhub/',
    description: 'This is an Instagram Live Stream.',
  },
  {
    title: 'Cultural Fusion Hub Meet up!',
    start: '2023-08-26T09:30:00',
    end: '2023-08-26T12:00:00',
    stream: false,
    location: '池尻地区会館 第二会議室',
    googleMapsUrl: 'https://goo.gl/maps/eJ61w1NwFYnbgyqp7',
    instagramUrl: null,
    description: 'ミックスの子供たちとパパさん、ママさんのための交流会。英語でお歌を歌ったり バイリンガル教育についてお話したりしませんか？おもちゃ、お菓子飲み物（大人用）有。参加料500円',
  },
  {
    title: 'Field Trip',
    start: '2023-09-03T11:00:00',
    end: '2023-09-03T14:00:00',
    stream: false,
    location: '世田谷区立中央図書館プラネタリウム',
    googleMapsUrl: 'https://goo.gl/maps/r2xHgTyLUWPjuNes6',
    instagramUrl: null,
    description: '世界最高クラス1億4000万個の星々を見て涼しい時間を過ごしましょう。価格：大人 400円、子供（小学生・中学生）：100円 幼児（膝上に座る場合）：無料',
  },
];
