//events.js

export default [
  // {
  //   title: 'Event Example Title',
  //   start: '2023-07-22T14:00:00',
  //   end: '2023-07-22T15:30:00',
  //   location: '代沢地区会館',
  //   googleMapsUrl: 'https://goo.gl/maps/6Vu8mX3HmBWbEU8n8',
  //   description: 'Example description',
  // },
  // {
  //   title: 'Instagram Live Example',
  //   start: '2023-08-19T18:00:00',
  //   end: '2023-08-19T20:30:00',
  //   stream: true,
  //   location: 'Instagram',
  //   googleMapsUrl: null,
  //   instagramUrl: 'https://www.instagram.com/culturalfusionhub/',
  //   description: 'This is an Instagram Live Stream.',
  // },
  {
    title: 'Cultural Fusion Hub Meet up!',
    start: '2023-07-15T09:00:00',
    end: '2023-07-15T12:00:00',
    location: '代沢地区会館',
    stream: false,
    googleMapsUrl: 'https://goo.gl/maps/6Vu8mX3HmBWbEU8n8',
    instagramUrl: null,
    description:
      'ミックスキッズとそのママさん、パパさんの交流会。英語の本の読み聞かせもあります！おもちゃもたくさん準備していますので、お子様を連れて、お気軽にお越しください。お時間のある方は、交流会の後にランチや近場の夏祭りに行きましょう！',
  },
  {
    title: 'Field Trip',
    start: '2023-08-06T10:00:00',
    end: '2023-08-06T12:00:00',
    location: '消防博物館',
    stream: false,
    googleMapsUrl: 'https://goo.gl/maps/f1qV9NSW5iTZgPuAA',
    instagramUrl: null,
    description: 'ミックスの子供たちとパパさん、ママさんのための交流フィールドトリップ開催。歴代の消防車を見たり、ヘリコプターに乗ったりして子供たちを交流させましょう。',
  },
  {
    title: 'インスタライブ',
    start: '2023-08-20T09:30:00',
    end: '2023-08-20T10:30:00',
    stream: true,
    location: 'Instagram',
    googleMapsUrl: null,
    instagramUrl: 'https://www.instagram.com/culturalfusionhub/',
    description: 'テーマ：カルチャルフュージョンハブを立ち上げたきっかけについて',
  },
  {
    title: 'Cultural Fusion Hub Meet up!',
    start: '2023-08-26T09:30:00',
    end: '2023-08-26T12:00:00',
    stream: false,
    location: '池尻地区会館 第二会議室',
    googleMapsUrl: 'https://goo.gl/maps/eJ61w1NwFYnbgyqp7',
    instagramUrl: null,
    description: 'ミックスの子供たちとパパさん、ママさんのための交流会。英語でお歌を歌ったり バイリンガル教育についてお話したりしませんか？おもちゃ、お菓子飲み物（大人用）有。参加料500円',
  },
  {
    title: 'Field Trip',
    start: '2023-09-03T11:00:00',
    end: '2023-09-03T14:00:00',
    stream: false,
    location: '世田谷区立中央図書館プラネタリウム',
    googleMapsUrl: 'https://goo.gl/maps/r2xHgTyLUWPjuNes6',
    instagramUrl: null,
    description: '世界最高クラス1億4000万個の星々を見て涼しい時間を過ごしましょう。価格：大人 400円、子供（小学生・中学生）：100円 幼児（膝上に座る場合）：無料',
  },
  {
    title: 'シモキタおやこまちつどい市',
    start: '2023-09-09T13:00:00',
    end: '2023-09-09T17:00:00',
    stream: false,
    location: '下北線路街空き地',
    googleMapsUrl: 'https://goo.gl/maps/bdBkCcrsVEcuntcD9',
    instagramUrl: null,
    description: '親子で楽しめるワークショップ、ステージプログラム等１１時から開催しています。週末、お子様とのお出かけ先として是非お越しください。Cutlrual Fusion Hubは１３時からブースを出展しています。お時間のある方は、是非遊びに来てください！',
  },
  {
    title: 'Meetup！',
    start: '2023-09-17T09:30:00',
    end: '2023-09-17T12:00:00',
    stream: false,
    location: '池尻地区会館',
    googleMapsUrl: 'https://goo.gl/maps/eJ61w1NwFYnbgyqp7',
    instagramUrl: null,
    description: 'ミックスキッズを遊ばせながら、パパさん、ママさんも情報交換や交流しませんか？９月といえば、お月見。キッズは、粘土細工や工作でお月見を楽しみましょう。パパさん、ママさんの話し合いのテーマは、異文化育児／教育の中での新たな発見です。カップル内で、育児においても様々な文化の違いを体験します。そこでの悩み、笑い、苦労を皆さんで共有できたらと思います！お時間の有る方は、その後、地区会館にあるレストランでランチ会も！',
  },
  {
    title: 'ナイトアウト',
    start: '2023-09-28T17:30:00',
    end: '2023-09-28T20:00:00',
    stream: false,
    location: '下北沢エリア',
    googleMapsUrl: 'https://goo.gl/maps/bdBkCcrsVEcuntcD9',
    instagramUrl: null,
    description: '去年から、下北沢エリアで実施されているムーンアートナイト。去年は、満月やうさぎのインスタレーション、とても素敵でしたが、今年も実施するようです。保育園、幼稚園、学校帰りに、みんなで集まってムーンアートナイトを見に行って、そのあとに、ディナー会で楽しみましょう。',
  },
];
